package simpaths.model.enums;

public enum TimeSeriesVariable {
    CareProvisionAdjustment,
    CarerWageRate,
    FixedRetirementAge,
    GDP,
    HighEducationRate,
    Inflation,
    LowEducationRate,
    PartnershipAdjustment,
    FertilityAdjustment,
    DisabilityAdjustment,
    UtilityAdjustment,
    UtilityAdjustmentSingleMales,
    UtilityAdjustmentACMales,
    UtilityAdjustmentSingleFemales,
    UtilityAdjustmentACFemales,
    UtilityAdjustmentCouples,
    UtilityAdjustmentMaleWithDep,
    UtilityAdjustmentFemaleWithDep,
    RetirementAdjustment,
    InSchoolAdjustment,
    WageGrowth,
}
